#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef WORDS_BIGENDIAN

#undef ENABLE_DPKG
#undef ENABLE_RPM
#undef STATIC_RPM
#undef RPM_VERSION
#undef RPM_MAJOR_VERSION
#undef RPM_MINOR_VERSION
#undef RPM_MICRO_VERSION
#undef HAVE_BZ2
