#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef WORDS_BIGENDIAN

#undef ENABLE_DPKG
#undef ENABLE_RPM
#undef STATIC_RPM
#undef RC_RPM4
#undef STRICT_RPM_ORDER
